version: '3'

services:
  postgres:
    image: postgres:11-alpine
    container_name: postgres_container
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "pizzahuntdb"
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pixo"
      PGADMIN_DEFAULT_PASSWORD: "password"
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "5555:80"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    pgadmin: